name: Build & Push Docker Image to container image registry

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        target-cpu: [znver3, znver2, skylake, haswell, sandybridge]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Get flavored tags
        id: tags
        run: |
          if [ "${{ matrix.target-cpu }}" = "haswell" ]; then echo ::set-output name=tag::ghcr.io/${{ steps.string.outputs.lowercase }}:latest; else echo ::set-output name=tag::ghcr.io/${{ steps.string.outputs.lowercase }}:latest-${{ matrix.target-cpu }}; fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: ${{ steps.tags.outputs.tag }}
          push: true
          build-args: |
            TARGET_CPU=${{ matrix.target-cpu }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max